// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh11XYQ8QgAaIVwH983AEyne_5X-4oVNI',
    appId: '1:523706652800:web:242e8f940c1e0f0dcb2e65',
    messagingSenderId: '523706652800',
    projectId: 'icaro-3fbd9',
    authDomain: 'icaro-3fbd9.firebaseapp.com',
    storageBucket: 'icaro-3fbd9.firebasestorage.app',
    measurementId: 'G-2QZEVX9S5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFGF64hGiSjL1Nde6Ip7Yz4dZSJr4sxQo',
    appId: '1:523706652800:android:d07243cf6299038ecb2e65',
    messagingSenderId: '523706652800',
    projectId: 'icaro-3fbd9',
    storageBucket: 'icaro-3fbd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkryK9omYFNFxHx01B3BT58rqc01TsRNw',
    appId: '1:523706652800:ios:75f8e8cfa4f596adcb2e65',
    messagingSenderId: '523706652800',
    projectId: 'icaro-3fbd9',
    storageBucket: 'icaro-3fbd9.firebasestorage.app',
    iosBundleId: 'com.example.icaro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkryK9omYFNFxHx01B3BT58rqc01TsRNw',
    appId: '1:523706652800:ios:75f8e8cfa4f596adcb2e65',
    messagingSenderId: '523706652800',
    projectId: 'icaro-3fbd9',
    storageBucket: 'icaro-3fbd9.firebasestorage.app',
    iosBundleId: 'com.example.icaro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh11XYQ8QgAaIVwH983AEyne_5X-4oVNI',
    appId: '1:523706652800:web:400c412eab6cb305cb2e65',
    messagingSenderId: '523706652800',
    projectId: 'icaro-3fbd9',
    authDomain: 'icaro-3fbd9.firebaseapp.com',
    storageBucket: 'icaro-3fbd9.firebasestorage.app',
    measurementId: 'G-5G8ZRYJ5NP',
  );
}
